version: '3'

services:
  db:
    build: ./BD
    container_name: dbBanca
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - dev-net
    ports:
      - "3306:3306"

  app:
    build: ./API
    container_name: devel
    stdin_open: true 
    volumes:
      - ./API:/home/node/
    networks:
      - dev-net
    ports:
      - "8000:8000"
    links:
      - db

  
networks:
    dev-net:
      driver: bridge
