-- MySQL Script generated by MySQL Workbench
-- vie 19 abr 2019 00:19:13 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banca` DEFAULT CHARACTER SET utf8 ;
USE `banca` ;

-- -----------------------------------------------------
-- Table `banca`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banca`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banca`.`TipoCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banca`.`TipoCuenta` (
  `idTipoCuenta` INT NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTipoCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banca`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banca`.`Cuenta` (
  `idCuenta` INT NOT NULL,
  `NumeroCuenta` VARCHAR(20) NOT NULL,
  `SaldoActual` VARCHAR(45) NOT NULL DEFAULT 0,
  `idTipoCuenta` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCuenta`, `idTipoCuenta`, `idCliente`),
  INDEX `fk_Cuenta_TipoCuenta_idx` (`idTipoCuenta` ASC),
  INDEX `fk_Cuenta_Cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Cuenta_TipoCuenta`
    FOREIGN KEY (`idTipoCuenta`)
    REFERENCES `banca`.`TipoCuenta` (`idTipoCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuenta_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `banca`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banca`.`Transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banca`.`Transaccion` (
  `idTransaccion` INT NOT NULL,
  `Fecha` TIMESTAMP(6) NOT NULL,
  `Tipo` INT NOT NULL,
  `Monto` DECIMAL NOT NULL,
  `SaldoResultante` DECIMAL NOT NULL,
  `idCuenta` INT NOT NULL,
  PRIMARY KEY (`idTransaccion`, `idCuenta`),
  INDEX `fk_Transaccion_Cuenta1_idx` (`idCuenta` ASC),
  CONSTRAINT `fk_Transaccion_Cuenta1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `banca`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
