-- MySQL Script generated by MySQL Workbench
-- jue 25 abr 2019 23:47:50 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banca` DEFAULT CHARACTER SET utf8 ;
USE `banca` ;

-- -----------------------------------------------------
-- Table `banca`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banca`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banca`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banca`.`Cuenta` (
  `NumeroCuenta` VARCHAR(20) NOT NULL,
  `SaldoActual` DECIMAL NOT NULL DEFAULT 0,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cuenta_Cliente_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Cuenta_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `banca`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banca`.`Asociados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banca`.`Asociados` (
  `idCliente` INT NOT NULL,
  `idSocio` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `idSocio`),
  INDEX `fk_Asociados_Cliente2_idx` (`idSocio` ASC),
  CONSTRAINT `fk_Asociados_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `banca`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asociados_Cliente2`
    FOREIGN KEY (`idSocio`)
    REFERENCES `banca`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CUENTAS
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Ricardo', 'Cutz', 'ric@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Uziel', 'Esquite', 'uzi@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Jorge', 'Say', 'jorge@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Chepe', 'Paz', 'chepe@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Beto', 'Paz', 'beto@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Kevin', 'Espana', 'kevin@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Kriste', 'Gutierrez', 'kriss@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Jhosef', 'Caceres', 'joseph@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Christopher', 'Orellana', 'cris@gmail.com', '123');
INSERT INTO `banca`.`Cliente`(`Nombre`, `Apellido`, `Correo`, `Password`) VALUES('Christian', 'Ramos', 'christian@gmail.com', '123');

-- CUENTAS
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('RIC123', 0, 1);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('UZI123', 0, 2);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('JOR123', 0, 3);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('CHP123', 0, 4);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('BET123', 0, 5);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('KEV123', 0, 6);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('KRS123', 0, 7);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('JHS123', 0, 8);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('CHR123', 0, 9);
INSERT INTO `banca`.`Cuenta`(`NumeroCuenta`, `SaldoActual`, `idCliente`) VALUES('CTI123', 0, 10);
-- ASOCIACIONES
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(1,2);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(1,3);

INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(2,1);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(2,10);

INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(3,5);

INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(4,1);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(4,9);

INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(6,7);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(6,3);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(6,4);

INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(9,1);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(9,2);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(9,3);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(9,4);

INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(10,3);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(10,4);
INSERT INTO `banca`.`Asociados`(`idCliente`, `idSocio`) VALUES(10,5);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
